# Generated by Django 5.0.8 on 2024-08-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='text',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='cake',
            name='description',
            field=models.TextField(max_length=70),
        ),
    ]
