# Generated by Django 5.0.8 on 2024-08-15 18:22

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_rename_text_order_comment_alter_cake_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='saled',
            field=models.BooleanField(default=False, help_text='продан'),
        ),
        migrations.AddField(
            model_name='cake',
            name='weight',
            field=models.IntegerField(default=None, help_text='масса в граммах'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cake',
            name='description',
            field=models.TextField(help_text='описание торта', max_length=70),
        ),
        migrations.AlterField(
            model_name='cake',
            name='image',
            field=models.ImageField(help_text='фото торта', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='name',
            field=models.CharField(help_text='название торта', max_length=50),
        ),
        migrations.AlterField(
            model_name='cake',
            name='price',
            field=models.IntegerField(help_text='цена торта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(help_text='коментарий заказчика'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(help_text='имя заказчика', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='телефон заказчика', max_length=128, region=None),
        ),
    ]
