# Generated by Django 5.0.8 on 2024-11-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0003_cake_saled_cake_weight_alter_cake_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(help_text='номер телефона', max_length=20)),
                ('telegram', models.CharField(help_text='ссылка на телеграм', max_length=50)),
                ('instagram', models.CharField(help_text='ссылка на инстаграм', max_length=50)),
                ('address', models.CharField(help_text='адрес', max_length=150)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cake',
            options={'ordering': ['-id']},
        ),
    ]
